resources: "resources.yaml"
samples: "samples_pacbio.tsv"
units: "units_pacbio.tsv"

default_container: "docker://hydragenetics/common:3.1.1"

aligner: "pbmm2"

reference:
  fasta: "reference/HES45.fna"
  fai: "reference/HES45.fna.fai"
  design_bed: "reference/twist_DNA_solid.HES45.annotated.bed"

whatshap_haplotag:
  container: "docker://hydragenetics/whatshap:2.2"
  extra: " --ignore-read-groups"

whatshap_phase:
  container: "docker://hydragenetics/whatshap:2.2"
  extra: ""
