resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:3.1.1"

reference:
  annovar: "reference/annovar"
  fasta: "reference/HES45.fna"
  fai: "reference/HES45.fna.fai"
  design_bed: "reference/twist_DNA_solid.HES45.annotated.bed"

deepmosaic_draw:
  container: "library://sanglee8888/deepmosaic/deepmosaic:sha256.28b3dd3b3ab1daa63b53d627c3fba3e6b4da38447ccdb9c7abc073718ff9453e"

deepmosaic_predict:
  container: "library://sanglee8888/deepmosaic/deepmosaic:sha256.28b3dd3b3ab1daa63b53d627c3fba3e6b4da38447ccdb9c7abc073718ff9453e"

mosaicforecast_phasing:
  container: "docker://yanmei/mosaicforecast_hg38:0.0.1"
  f_format: "bam" # cram/bam
  umap: "/usr/local/bin/k24.umap.wg.bw"

### Need small dataset to do tests ###

# mosaicforecast_input:
#   bcftools_filter: "--exclude 'FILTER!=\"PASS\" || FORMAT/DP<8'"

# mosaicforecast_readlevel:
#   container: "docker://yanmei/mosaicforecast_hg38:0.0.1"
#   f_format: "bam" # cram/bam
#   umap: "/usr/local/bin/k24.umap.wg.bw"

# mosaicforecast_genotype_prediction:
#   container: "docker://yanmei/mosaicforecast_hg38:0.0.1"
#   model_trained_SNP: "reference/150xRFmodel_addRMSK_Refine.rds" 
#   model_trained_INS: "reference/insertions_250x.RF.rds" 
#   model_trained_DEL: "reference/deletions_250x.RF.rds"
#   model_type_SNP: "Refine"  # phase/refine
#   model_type_INS: "Phase"  # phase/refine
#   model_type_DEL: "Phase"  # phase/refine